# fly.toml app configuration file generated for pdf-alchemist on 2023-11-09T08:46:16+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pdf-alchemist"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
